service: retail-copilot-backend
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
  httpApi:
    cors: true
  environment:
    DATABASE_URL: ${env:DATABASE_URL}
    ANTHROPIC_API_KEY: ${env:ANTHROPIC_API_KEY}

package:
  patterns:
    - "!src/**"
    - "!tsconfig.json"
    - "!.git/**"
    - "!.github/**"
    - "!node_modules/prisma/**"
    - "!node_modules/@prisma/engines/**"
    - "!node_modules/typescript/**"
    - "!node_modules/@types/**"

functions:
  api:
    handler: dist/server.handler
    events:
      - httpApi:
          path: "/{proxy+}"
          method: "*"
